# Generated by Django 5.0.6 on 2024-06-21 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "default_permissions": (),
                "permissions": (
                    ("add_category", "Create Category"),
                    ("view_category", "View Category"),
                    ("change_category", "Update Category"),
                    ("delete_category", "Delete Category"),
                ),
            },
        ),
    ]
