# Generated by Django 5.0.6 on 2024-06-20 23:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0002_category_course_category"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chapter",
            options={},
        ),
        migrations.AlterModelOptions(
            name="content",
            options={},
        ),
        migrations.AlterModelOptions(
            name="coursetutor",
            options={},
        ),
        migrations.AlterModelOptions(
            name="enrollment",
            options={},
        ),
        migrations.AddConstraint(
            model_name="chapter",
            constraint=models.UniqueConstraint(
                fields=("course", "position"), name="unique_position_per_course"
            ),
        ),
        migrations.AddConstraint(
            model_name="content",
            constraint=models.UniqueConstraint(
                fields=("chapter", "position"), name="unique_position_per_chapter"
            ),
        ),
        migrations.AddConstraint(
            model_name="coursetutor",
            constraint=models.UniqueConstraint(
                fields=("course", "tutor"), name="unique_tutor_in_course"
            ),
        ),
        migrations.AddConstraint(
            model_name="enrollment",
            constraint=models.UniqueConstraint(
                fields=("course", "learner"), name="unique_learner_in_course"
            ),
        ),
    ]
