# Generated by Django 5.0.6 on 2024-06-21 06:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0002_alter_category_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="TopicCompletionLog",
            new_name="ContentCompletionLog",
        ),
        migrations.AlterModelOptions(
            name="course",
            options={
                "default_permissions": (),
                "permissions": (
                    ("add_category", "Create Category"),
                    ("view_category", "View Category"),
                    ("change_category", "Update Category"),
                    ("delete_category", "Delete Category"),
                ),
            },
        ),
    ]
