# Generated by Django 5.0.6 on 2024-06-21 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0003_rename_topiccompletionlog_contentcompletionlog_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contentcompletionlog",
            options={
                "default_permissions": (),
                "permissions": (
                    ("add_completionlog", "Create Completion Log"),
                    ("view_completionlog", "View Completion Log"),
                    ("change_completionlog", "Update Completion Log"),
                    ("delete_completionlog", "Delete Completion Log"),
                ),
            },
        ),
    ]
