# Generated by Django 5.0.6 on 2024-06-21 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0003_alter_chapter_options_alter_content_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="content",
            name="textUrl",
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name="content",
            name="videoUrl",
            field=models.URLField(null=True),
        ),
    ]
