# Generated by Django 5.0.6 on 2024-06-21 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0004_alter_contentcompletionlog_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="course",
            options={
                "default_permissions": (),
                "permissions": (
                    ("add_course", "Create Course"),
                    ("view_course", "View Course"),
                    ("change_course", "Update Course"),
                    ("delete_course", "Delete Course"),
                ),
            },
        ),
    ]
