# Generated by Django 5.0.6 on 2024-06-21 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0004_alter_content_texturl_alter_content_videourl"),
    ]

    operations = [
        migrations.AlterField(
            model_name="content",
            name="textUrl",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="content",
            name="videoUrl",
            field=models.URLField(blank=True),
        ),
    ]
