# Generated by Django 5.0.6 on 2024-06-21 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0005_alter_course_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chapter",
            options={"ordering": ["position"]},
        ),
        migrations.AlterModelOptions(
            name="content",
            options={"ordering": ["position"]},
        ),
    ]
