# Generated by Django 5.0.6 on 2024-06-21 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0007_remove_chapter_islastchapter_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chapter",
            name="completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="content",
            name="completed",
            field=models.BooleanField(default=False),
        ),
    ]
