# Generated by Django 5.0.6 on 2024-06-21 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0008_chapter_completed_content_completed"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="content",
            name="textUrl",
        ),
        migrations.RemoveField(
            model_name="content",
            name="type",
        ),
        migrations.RemoveField(
            model_name="content",
            name="videoUrl",
        ),
        migrations.AddField(
            model_name="content",
            name="fileUrl",
            field=models.URLField(default=None),
            preserve_default=False,
        ),
    ]
