# Generated by Django 5.0.6 on 2024-06-21 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0009_remove_content_texturl_remove_content_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="content",
            name="fileUrl",
        ),
        migrations.AddField(
            model_name="content",
            name="content",
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
