# Generated by Django 5.0.6 on 2024-06-21 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0010_remove_content_fileurl_content_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="content",
            name="content",
            field=models.URLField(),
        ),
    ]
