# Generated by Django 5.0.6 on 2024-06-23 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0012_alter_content_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='type',
            field=models.CharField(choices=[('HTML', 'HTML'), ('VIDEO', 'VIDEO')], default=None),
            preserve_default=False,
        ),
    ]
